# Generated by Django 5.2.8 on 2025-11-23 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='document_status',
            field=models.CharField(blank=True, choices=[('Є всі документи', 'Є всі документи'), ('Документи відсутні', 'Документи відсутні'), ('Є лише рапорт', 'Є лише рапорт'), ('Часткові документи', 'Часткові документи'), ('Є висновок ВЛК', 'Є висновок ВЛК'), ('Є наказ', 'Є наказ')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='issue_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='situation_stage',
            field=models.CharField(blank=True, choices=[('Ситуація тільки виникла', 'Ситуація тільки виникла'), ('Рапорт подано', 'Рапорт подано'), ('Отримано відмову', 'Отримано відмову'), ('Службове розслідування', 'Службове розслідування'), ('Досудовий етап', 'Досудовий етап'), ('Судовий розгляд', 'Судовий розгляд')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_status', models.CharField(choices=[('Мобілізований', 'Мобілізований'), ('Контрактник', 'Контрактник'), ('Строковик', 'Строковик'), ('Офіцер', 'Офіцер'), ('Звільнений', 'Звільнений'), ('Ветеран', 'Ветеран'), ('Член родини', 'Член родини'), ('Курсант', 'Курсант')], max_length=50)),
                ('service_type', models.CharField(choices=[('ЗСУ', 'ЗСУ'), ('НГУ', 'НГУ'), ('ТрО', 'ТрО'), ('ДПСУ', 'ДПСУ'), ('ССО', 'ССО'), ('Поліція', 'Поліція'), ('Нацгвардія', 'Нацгвардія')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
