# Generated by Django 5.2.8 on 2025-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatsession_userquery_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
