# Generated by Django 5.2.11 on 2026-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userquery_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Stores the original document in JSON format', null=True),
        ),
    ]
